name: Build Go app and push to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Go app
      working-directory: ./server
      run: go build -o ../build/go-app.exe

    - name: Test Go app
      working-directory: ./server
      run: go test ./...

    - name: Copy static template files
      run: xcopy /i templates build\\templates

    - name: Copy static public files
      run: xcopy /i public build\\public

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: FixMyStreetBackend
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
